apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eh6d5drsm-go 
  janus-idp.io/tekton: eh6d5drsm-go
  backstage.io/kubernetes-id: eh6d5drsm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eh6d5drsm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml