apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eh6d5drsm-go-gitops
  description: This is GitOps manifest for eh6d5drsm-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=eh6d5drsm-go
    backstage.io/kubernetes-id: eh6d5drsm-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: eh6d5drsm-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:eh6d5drsm-go
