apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eh6d5drsm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eh6d5drsm-go 
  name: eh6d5drsm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eh6d5drsm-go 
